### PR TITLE
Get the default language from LANG env variable #25

### PR DESCRIPTION
**Pull request by juanpabloaj**

### CODE REVIEW

**Comment by aetheon** [comment]
Hi @juanpabloaj I'll merge the code sometime during this week. Tks.

**Comment by aetheon** [comment]
sorry @juanpabloaj I have to reject the PR due to build errors and method duplication. I'll publish a new version with this implemented. Tks anyway.

**Comment by juanpabloaj** [comment]
@aetheon I check the build message and I think the problem is with the dependencies (not with the commit changes)

https://travis-ci.org/divhide/node-subtitler/builds/136966093

I have the same problem when I use 

    npm install

I only can install the production dependencies 

    npm install --production

**Comment by aetheon** [comment]
@juanpabloaj you're right. I fixed that before publishing the new version. Thanks.

**Pull request closed without merging**
